### PR TITLE
Genome class to handle fasta files and chromsizes throughout package

### PR DESCRIPTION
**Pull request by LukasMahieu**
## Updates

Added a genome class and a register_genome(...) function to make working with genomes easier.
Updated all functions in the package to allow for this genome instance as input while keeping backward compatibility (you can still provide a path if you want).
Added unit tests.

The advantages of this are:

- The Genome class will deduce the chromsizes from the Fasta if not provided
- The Genome class ensures that we only open one pysam.FastaFile in a session instead of multiple in different functions
-  A user can use crested.register_genome(...) at the beginning of a session (notebook or script). If done, all the other functions that require a genome_path and/or chromsizes will use the registered genome if not provided. This is important for the functional refactor I'm working on since many functions will require a genome as input

@casblaauw The genome also has an "annotations" attribute that is currently unused and not implemented, but we should use that when working with genes.

Haven't updated the tutorial yet, will do so when I finish the functional refactor.

There's one breaking change in this PR, since the crested.tl.data.AnnDataset now only expects a crested.Genome object instead of a genome_path and chromsizes. However, since this is more of a backend functionality that a normal user will never have used, I don't think this is such a big deal.

## Example usage
Genome class
```
>>> genome = crested.Genome(
...     fasta="tests/data/test.fa",
...     chrom_sizes="tests/data/test.chrom.sizes",
... )
>>> print(genome.fasta)
<pysam.libcfaidx.FastaFile at 0x7f4d8b4a8f40>
>>> print(genome.chrom_sizes)
{'chr1': 1000, 'chr2': 2000}
>>> print(genome.name)
test
```

Registering
```
>>> genome = Genome(
...     fasta="tests/data/hg38.fa",
...     chrom_sizes="tests/data/test.chrom.sizes",
... )
>>> crested.register_genome(genome)
INFO Genome hg38 registered.
```

### CODE REVIEW

**Review by nkempynck — APPROVED** [review]
looks good to me

**Comment by LukasMahieu** [comment]
Yes, good point. We indeed already had the crested.utils.fetch_sequences (which wasn't in the tutorials anywhere, only the API docs) but now it would make more sense to only have it as a method in the Genome class

**Review by casblaauw — APPROVED** [review]
Looks great! Added a final missed function (the region resizing one) and reran the tutorial with this included. All good on my end, have a look at `fetch` and my other changes if you want and merge at your leisure.

**Comment by LukasMahieu** [comment]
Thanks, good changes. I made some minor updates in the notebooks still and I'm merging (and releasing a new version).

**Pull request merged**
